---
- hosts: all
  collections:
    - ansible.windows

  tasks:
    - name: Get list of all users
      win_shell: Get-LocalUser | Where-Object {$_.Enabled -eq $True} | Select Name | Format-Table -HideTableHeaders
      register: enabled_users
    - name: Remove obsolete shortcut
      win_file:
        username: "{{ enabled_users }}"
        path: C:\Users\$username\Desktop\obsoleteShortcut.exe
        state: absent
        remove_multiple: true
      loop: "{{ enabled_users.stdout_lines[1:-2] }}"
