---
- hosts: all
  collections:
    - ansible.windows

  tasks:
    - name: Remove obsolete shortcut
      win_file:
        path: C:\Users\usr-nagios\Desktop\obsoleteShortcut.exe
        state: absent

