---
# Playbook Suppression des raccourcis obsolètes des profils utilisateurs
- hosts: all
  collections:
    #Nom des collections à utiliser
    - ansible.windows

  tasks:
    # Obtention d'une liste contenant tous les utilisateurs
    - name: Get list of all users
      win_shell: Get-LocalUser | Where-Object {$_.Enabled -eq $True} | Select Name | Format-Table -HideTableHeaders
      register: enabled_users

    # Suppression des raccourcis obsolètes des profils utilisateurs présents dans la liste 
    - name: Remove obsolete shortcut
      win_file:
        # Nom du raccourci à supprimer
        file: 'obsoleteShortcut.exe'
        # Nom du chemin d'accès du raccourci à supprimer
        path: 'C:\Users\{{ item }}\Desktop\'
        # État du raccourci à supprimer (absent ou present)
        state: absent
      loop: "{{ enabled_users.stdout_lines[1:-2] | regex_replace(' ', '') }}"
