---
- hosts: all
  collections:
    - ansible.windows

  tasks:
    - name: Remove obsolete shortcut
      win_file:
        path: \%CSIDL_COMMON_DESKTOPDIRECTORY%\obsoleteShortcut.exe
        state: absent
